### ISSUE TITLE
Check readme grammar

### ISSUE THREAD

**Issue by vinird** [vinird/tutorialjs#2]
This is a new repository so we need lots of help. Feel free to check the readme.md grammar and make any correction you consider necessary. Any change to understand better what is this repo for.

**Comment by jacobhlyon** [comment]
@vinird I can help out with this!

**Comment by vinird** [comment]
@jacobhlyon yes please!

**Comment by mefarazath** [comment]
Feel free to check the **reamed.md** --> readme.md
:wink:

**Comment by genesisrrios** [comment]
Hi, I can help with the README.md grammar.

**Comment by vinird** [comment]
@genesisrrios @mefarazath @jacobhlyon Any suggestion is welcome.

**Comment by mefarazath** [comment]
@vinird Added a PR #4 with some corrections.
